project:
  type: book
  #output-dir: _book # by default

book:
  title: "My Quarto Book"
  author: "Your Name Here"
  date: "6/10/2024"
  chapters:
    - index.qmd
    - about.qmd
    - article.md
    - contact.md
    - python-example.qmd
    - demo-notebook.ipynb
    - reference/index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    # cite-method: biblatex
  epub:
    cover-image: cover.png


# only if you are using autodoc:
# https://machow.github.io/quartodoc/get-started/basic-docs.html
quartodoc:
  # the name used to import the package you want to create reference docs for
  package: my_project

  # write sidebar data to this file
  #sidebar: _sidebar.yml

  #style: pkgdown

  # directory relative to current (docs/)
  dir: reference

  sections:
    - title: Some functions
      desc: Functions to exemplify auto documentation.
      contents:
        #- get_object        # function: quartodoc.get_object
        #- ast.preview       # submodule func: quartodoc.ast.preview
        #- MdRenderer        # class: quartodoc.MdRenderer
        #- MdRenderer.render # method: quartodoc.MDRenderer.render
        #- renderers         # module: quartodoc.renderers
        - calculator.Calculator
        - formatter.to_usd
