project:
  type: book
  output-dir: "_build"
  preview:
    port: 4567
    browser: true

# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "My Book"
  author: "Norah Jones"
  date: "last-modified" # "7/24/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

  # https://quarto.org/docs/websites/website-tools.html#google-analytics
  #google-analytics: "G-..."

  site-url: https://s2t2.github.io/quarto-book-template/
  repo-url: https://github.com/s2t2/quarto-book-template
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub, docx]

  sharing: [twitter, facebook]
  # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true

  # https://quarto.org/docs/reference/projects/books.html#search
  search: true
    #location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  cover-image: images/cover.png
  #favicon: images/favicon.ico

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  sidebar:
    logo: images/quarto-dark-bg.jpeg


  chapters:
    - index.qmd
    - intro.qmd

    - chapter.qmd
    - another-chapter.qmd

    - part: "Part I"
      #href:  part-1/index.qmd
      chapters:
        - part-1/chapter.qmd
        - part-1/another-chapter.qmd

    #- part: "Part II"
    #  #href:  part-2/index.qmd
    #  chapters:
    #    - part-2/chap-3.qmd
    #    - part-2/chap-4.qmd

    - summary.qmd
    - references.qmd

    - "-------------"

  appendices:
    - appendix.qmd
    - another-appendix.qmd

  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  #page-footer:
  #  center: "&copy; Copyright 2024, Your Name Here"


bibliography: references.bib

format:
  html:
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light: default #flatly
      dark: darkly

    #css: styles.css
  pdf:
    documentclass: scrreprt
