#
# QUARTO WEBSITES:
# https://quarto.org/docs/websites/
# https://github.com/jhelvy/jhelvy_quarto/blob/main/_quarto.yml
# https://github.com/pingfan-hu/Pingfan-Website/blob/main/_quarto.yml
#
# QUARTO BOOKS:
# https://quarto.org/docs/books/
# https://github.com/jjallaire/visualization-curriculum/blob/master/_quarto.yml
# https://github.com/hadley/r4ds/blob/main/_quarto.yml
#

project:
  type: book
  output-dir: _book # by default
  preview:
    port: 5555 # use the same port instead of a new one each time
    browser: true

#
# BOOK
# https://quarto.org/docs/reference/projects/books.html#section
#

book:
  title: "My Quarto Book" # controls name of PDF file in "_book" dir
  subtitle: "A Subtitle"
  author: "Your Name Here"
  date: "6/10/2024"
  #abstract: "Lorem Ipsum"
  #description: "Some HTML Metadata"
  output-file: "my-book"
  #edition: 3

  site-url: https://s2t2.github.io/quarto-book-template/
  repo-url: https://github.com/s2t2/quarto-book-template
  repo-branch: main
  repo-actions: [edit, issue, source]

  search: true
  reader-mode: true
  page-navigation: true # adds buttons at bottom of page
  downloads: [pdf, epub]
  #google-analytics: "G-XXXXXX"
  #bread-crumbs: true

  image: assets/cover.png
  cover-image: assets/cover.png
  favicon: assets/cover.png

  navbar:
    title: "Quarto Book Template"
    #logo: cover.png
    search: true
    pinned: true
    collapse: true
    right:
      - icon: github
        href: https://github.com/s2t2/quarto-book-template
        text: GitHub Repo
      - icon: globe
        href: https://prof-rossetti.org
        text: Academic Site
    #left:
    #  - icon: github
    #    href: https://github.com/s2t2/quarto-book-template
    #    text: GitHub Repo Left
    #  - icon: globe
    #    href: https://prof-rossetti.org
    #    text: Academic Site Left


  chapters:
    - index.qmd
    - about.qmd
    - contact.md
    - article.md
    # NOTE: EPUB and DOCX do not currently support parts. When rendering, the parts will be ignored.
    #- part: "Code Execution"
    - part: code-execution.md
      chapters:
        - python-example.qmd
        #- r-example.qmd
        - demo-notebook.ipynb
    # auto documentation:
    - reference/index.qmd

  #appendices:
  #  - tools.qmd
  #  - resources.qmd


  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  #sidebar:
  #  style: docked # docked or floating
  #  background: light

  #page-footer:
  #  left: |
  #    This is a footer. &copy; 2024 Your Name Here.
  #  right: |
  #    This book was built with <a href="https://quarto.org/">Quarto</a>.


#
# FORMAT
#

format:
  html:
    # BOOTSWATCH THEME
    # https://quarto.org/docs/output-formats/html-themes.html
    # https://bootswatch.com/
    #theme: yeti #yeti #superhero #litera #cosmo # [cosmo, styles.scss]
    #css: styles.css
    theme:
      light: litera #flatly #yeti
      dark: [superhero, assets/dark-theme-overrides.scss] #darkly #superhero

    toc: true
    #toc-expand: 2
    #toc-depth: 5
    #toc-location: right
    number-sections: false

    code-copy: true # true, false, hover

    #lightbox: true
    #backgroundcolor: "#F8F7F0"

    #anchor-sections: true
    #smooth-scroll: true
    #link-external-newwindow: true
    #link-external-icon: false
    # This is to include fontawesome and academic icons in the headers:
    #include-in-header: "_includes/header.html"

  pdf:
    documentclass: scrreprt

    # cite-method: biblatex

    # https://quarto.org/docs/books/book-structure.html#creating-an-index
    #include-in-header:
    #  text: |
    #    \usepackage{makeidx}
    #    \makeindex
    #include-after-body:
    #  text: |
    #    \printindex

  epub:
    cover-image: cover.png




bibliography: references.bib

# control caching of files
# IPYNB files not executed by default
#execute:
#  freeze: false
#  warning: false

# a comments related plugin
# https://web.hypothes.is/
#comments:
#  hypothesis: true

# if you are using autodoc:
# https://machow.github.io/quartodoc/get-started/basic-docs.html
quartodoc:
  # the name used to import the package you want to create reference docs for
  package: my_project

  # write sidebar data to this file
  #sidebar: _sidebar.yml

  #style: pkgdown

  # directory relative to current (docs/)
  dir: reference

  sections:
    - title: Some functions
      desc: Functions to exemplify auto documentation.
      contents:
        #- get_object        # function: quartodoc.get_object
        #- ast.preview       # submodule func: quartodoc.ast.preview
        #- MdRenderer        # class: quartodoc.MdRenderer
        #- MdRenderer.render # method: quartodoc.MDRenderer.render
        #- renderers         # module: quartodoc.renderers
        - calculator.Calculator
        - formatter.to_usd
