# https://quarto.org/docs/books/

project:
  type: book
  output-dir: _build_book

book:
  title: "my-book"
  author: "Your Name Here"
  date: "8/18/2024"
  chapters:
    - index.qmd
    - about.qmd
    - article.md
    - contact.md
    - python-example.qmd
    - demo-notebook.ipynb
    #- reference/index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    # cite-method: biblatex
  epub:
    cover-image: cover.png









# https://machow.github.io/quartodoc/get-started/basic-docs.html
quartodoc:
  # the name used to import the package you want to create reference docs for
  package: my_project

  # directory relative to current (docs/)
  dir: reference

  sections:
    - title: Some functions
      desc: Functions to exemplify auto documentation.
      contents:
        - calculator.Calculator
        - formatter.to_usd
